#### [ Numpy ndarray 1D 변환 ]
- flatten() 함수 / 메서드 : 다른 메모리 공간에 저장
- ravel() 함수 / 메서드 : 동일 데이터 메모리 공유

In [1]:
## 모듈 로딩
import numpy as np

In [2]:
## ndarray 객체
n1 = np.array([[11, 22], [33, 44], [55, 66]])
n1

array([[11, 22],
       [33, 44],
       [55, 66]])

In [3]:
# ND => 1D 변환
n1.flatten()

array([11, 22, 33, 44, 55, 66])

In [4]:
n1

array([[11, 22],
       [33, 44],
       [55, 66]])

In [5]:
n1[0, 0] = 100
n1

array([[100,  22],
       [ 33,  44],
       [ 55,  66]])

In [6]:
n11 = n1.flatten()
n11

array([100,  22,  33,  44,  55,  66])

In [8]:
n1[0, 0] = 77
n11, n1

(array([100,  22,  33,  44,  55,  66]),
 array([[77, 22],
        [33, 44],
        [55, 66]]))

In [11]:
## ND => 1D 변환 ==> ravel()
print(n1)

n11 = n1.ravel()
print(n11)

[[77 22]
 [33 44]
 [55 66]]
[77 22 33 44 55 66]


In [13]:
## 원본 ndarray 데이터 변경 시 ravel() 저장된 데이터도 변경됨!
n1[0, 0] = 00
print(n1)
print(n11)

[[ 0 22]
 [33 44]
 [55 66]]
[ 0 22 33 44 55 66]
